const e=JSON.parse('{"key":"v-77101ed2","path":"/interview/knowledge/20210528-exception.html","title":"异常面试知识点","lang":"zh-CN","frontmatter":{"isOriginal":true,"category":"求职面试","tag":["面试","异常"],"description":"异常简介 异常类层次结构 从结构图可以看出，所有异常均继承自 Throwable 类，它有两个重要的子类：Exception 和 Error ，各自又包含大量子类。 1. Exception 程序本身可以处理的异常，又可以分为 受检异常 和 非受检异常 ，受检异常 可以用 try...catch... 语句进行捕获处理，而且能从异常中恢复。但 非受检异...","head":[["meta",{"property":"og:url","content":"https://zzdxy.github.io/zzdxy/zzdxy/interview/knowledge/20210528-exception.html"}],["meta",{"property":"og:site_name","content":"saltfish"}],["meta",{"property":"og:title","content":"异常面试知识点"}],["meta",{"property":"og:description","content":"异常简介 异常类层次结构 从结构图可以看出，所有异常均继承自 Throwable 类，它有两个重要的子类：Exception 和 Error ，各自又包含大量子类。 1. Exception 程序本身可以处理的异常，又可以分为 受检异常 和 非受检异常 ，受检异常 可以用 try...catch... 语句进行捕获处理，而且能从异常中恢复。但 非受检异..."}],["meta",{"property":"og:type","content":"article"}],["meta",{"property":"og:locale","content":"zh-CN"}],["meta",{"property":"og:updated_time","content":"2025-03-31T04:12:26.000Z"}],["meta",{"property":"article:author","content":"挣扎的咸鱼"}],["meta",{"property":"article:tag","content":"面试"}],["meta",{"property":"article:tag","content":"异常"}],["meta",{"property":"article:modified_time","content":"2025-03-31T04:12:26.000Z"}],["script",{"type":"application/ld+json"},"{\\"@context\\":\\"https://schema.org\\",\\"@type\\":\\"Article\\",\\"headline\\":\\"异常面试知识点\\",\\"image\\":[\\"\\"],\\"dateModified\\":\\"2025-03-31T04:12:26.000Z\\",\\"author\\":[{\\"@type\\":\\"Person\\",\\"name\\":\\"挣扎的咸鱼\\",\\"url\\":\\"https://zzdxy.github.io/zzdxy\\",\\"email\\":\\"8698305@qq.com\\"}]}"]]},"headers":[{"level":2,"title":"异常简介","slug":"异常简介","link":"#异常简介","children":[{"level":3,"title":"异常类层次结构","slug":"异常类层次结构","link":"#异常类层次结构","children":[]},{"level":3,"title":"Throwable 常用方法","slug":"throwable-常用方法","link":"#throwable-常用方法","children":[]},{"level":3,"title":"try-catch-finally 和 try-with-resources","slug":"try-catch-finally-和-try-with-resources","link":"#try-catch-finally-和-try-with-resources","children":[]}]},{"level":2,"title":"异常处理","slug":"异常处理","link":"#异常处理","children":[{"level":3,"title":"声明异常","slug":"声明异常","link":"#声明异常","children":[]},{"level":3,"title":"抛出异常","slug":"抛出异常","link":"#抛出异常","children":[]},{"level":3,"title":"捕获异常","slug":"捕获异常","link":"#捕获异常","children":[]}]},{"level":2,"title":"异常常见面试题","slug":"异常常见面试题","link":"#异常常见面试题","children":[{"level":3,"title":"Error 和 Exception 的区别？","slug":"error-和-exception-的区别","link":"#error-和-exception-的区别","children":[]},{"level":3,"title":"运行时异常和受检异常的区别？","slug":"运行时异常和受检异常的区别","link":"#运行时异常和受检异常的区别","children":[]},{"level":3,"title":"throw 和 throws 的区别？","slug":"throw-和-throws-的区别","link":"#throw-和-throws-的区别","children":[]},{"level":3,"title":"final、finally、finallize 的区别？","slug":"final、finally、finallize-的区别","link":"#final、finally、finallize-的区别","children":[]},{"level":3,"title":"常见的 RuntimeException 异常？","slug":"常见的-runtimeexception-异常","link":"#常见的-runtimeexception-异常","children":[]},{"level":3,"title":"JVM 如何处理异常？","slug":"jvm-如何处理异常","link":"#jvm-如何处理异常","children":[]}]}],"git":{"createdTime":1743394346000,"updatedTime":1743394346000,"contributors":[{"name":"zzdxy","email":"jiefav@163.com","commits":1}]},"readingTime":{"minutes":7.06,"words":2119},"filePathRelative":"interview/knowledge/20210528-exception.md","localizedDate":"2025年3月31日","copyright":{"author":"挣扎的咸鱼","license":"著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处"},"autoDesc":true,"excerpt":""}');export{e as data};
